### ISSUE TITLE
NPE at AbstractKafkaConnector.stopTask

### ISSUE THREAD

**Issue by rantav** [linkedin/brooklin#673]
### NPE at AbstractKafkaConnector.stopTask
After stopping a kafka mirroring task I noticed this NPE in the log. 

```
 [2019-11-27 14:12:00,896] INFO Stopping the DurableScheduledService for mirror-_test_replicator_1574862570_fc2f511c-af4f-43d1-8a35-28c3fe9627b2 (com.linkedin.datastream.common.DurableScheduledService)
 [2019-11-27 14:12:00,907] WARN Task mirror-_test_replicator_1574862570_d3b0ffd9-6d41-4217-93e7-574186923cc8(kafkaMirroringC), partitions=[0] took longer than 30000 ms to stop. Interrupting the thread. (com.linkedin.datastream.connectors.kafka.mirrormaker.KafkaMirrorMakerConnector)
 [2019-11-27 14:12:00,907] WARN Failed to check status of kafka connector tasks. (com.linkedin.datastream.connectors.kafka.mirrormaker.KafkaMirrorMakerConnector)
 java.lang.NullPointerException
 	at com.linkedin.datastream.connectors.kafka.AbstractKafkaConnector.stopTask(AbstractKafkaConnector.java:216)
 	at com.linkedin.datastream.connectors.kafka.AbstractKafkaConnector.restartIfNotRunning(AbstractKafkaConnector.java:196)
 	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649)
 	at com.linkedin.datastream.connectors.kafka.AbstractKafkaConnector.lambda$start$1(AbstractKafkaConnector.java:176)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 	at java.lang.Thread.run(Thread.java:748)
```

### Your environment
I am using this docker image `dongjinleekr/brooklin:1.0.0-2`, which internally uses brooklin `1.0.0`

* Operating System: `4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 Linux`
* Brooklin version: `1.0.0`
* Java version: `openjdk version "1.8.0_212"`
* Kafka version: `2.1.0`
* ZooKeeper version: `3.4.10`

### Steps to reproduce
It doesn't always repro.  
But in my case I started replicating a kafka topic and then after several minutes stopped. 
`maxTasks` was set to 50

### Expected behaviour
There should not be an NPE. 

### Actual behaviour
There's an NPE in the log. It didn't seem to affect the worker though, the only seen effect was in the log.

**Comment by ahmedahamid** [comment]
Hello @rantav ,

Thanks for reporting this issue. This issue was fixed in #682.
